### ISSUE TITLE
Is there a way to restyle controls?

### ISSUE THREAD

**Issue by disyakidneyshot** [kinescope/react-kinescope-player#11]
Hey guys!
Wanted to ask, is there a way to restyle the player controls in some way?
I know, that I can do it via `style` or `className` prop, but actually it is hard to use, because all your css classes have `hash` in name, which makes it totally unsafe to use as a css selectors for my custom styles :(
Maybe you can give me a hint or the only way will be to hide default controls and write custom from scratch?
Thanks for help!

**Comment by ToktogonovA** [comment]
> Hey guys! Wanted to ask, is there a way to restyle the player controls in some way? I know, that I can do it via `style` or `className` prop, but actually it is hard to use, because all your css classes have `hash` in name, which makes it totally unsafe to use as a css selectors for my custom styles :( Maybe you can give me a hint or the only way will be to hide default controls and write custom from scratch? Thanks for help!

Hi, did you manage to change the styles of the button? I encountered the same problem

**Comment by pushpush** [comment]
Hi. Changing the style only in the player settings: https://app.kinescope.io/workspace/players

**Comment by disyakidneyshot** [comment]
Ah, I see
Closing issue then
