### ISSUE TITLE
Language parameter doesn't make any change to an iframe player

### ISSUE THREAD

**Issue by disyakidneyshot** [kinescope/react-kinescope-player#4]
Hello there!
I've experienced some problems using this package, in particular with the `language` parameter.

This is how I use it
```javascript
import React, { useMemo } from 'react';
import KinescopePlayer from '@kinescope/react-kinescope-player';

export const Stream = ({ title, link }) => {

  const id = useMemo(() => {
    return link.match(/\/\d+$/)?.[0].slice(1) ?? '';
  }, [link]);

  return (
      <KinescopePlayer
        title={title}
        videoId={id}
        language="en"
        playbackRateButton={false}
      />
  );
};
```
`language` parameter wasn't taken into account by player and the language of the player is always `ru`, even if my browser/system language is `en`.

What am I doing wrong, could you help me pls?

**Comment by pushpush** [comment]
Hi! Doesn't work like that? https://codesandbox.io/s/player-mr6cn8!
What operating system and browser?

**Comment by disyakidneyshot** [comment]
Sorry, my fault
MacOS 13.5
Browser Chrome Version 115.0.5790.114
"@kinescope/react-kinescope-player": "^0.3.4"

The thing is, that I've tried to copy your `videoId`s parameter, and it works fine, and it's a simple video.
But we have a stream in our case (https://kinescope.io/204571695), and the message `Трансляция завершена` isn't localized

**Comment by pushpush** [comment]
Fixed. You can check

**Comment by disyakidneyshot** [comment]
Works nice, thank you so much!
