### ISSUE TITLE
Player fails to resume live stream

### ISSUE THREAD

**Issue by cgibin** [kinescope/react-kinescope-player#7]
It's not related to react component, could be easily reproduced via direct link (kinescope.io/embed/*), just dont know where to put this issue. 

If you do start/stop in OBS, player fails to resume stream with HLS_INVALID_PLAYLIST_HIERARCHY errors in console. Page reload fixes the issue

**Comment by vladzdev** [comment]
This should be fixed by now. Can you confirm that?

**Comment by cgibin** [comment]
Yes, it works now, thank you
