### ISSUE TITLE
Uncaught (in promise) Error: IFrame load failed: undefined     at iframe.player.js:1:121385

### ISSUE THREAD

**Issue by Nizomkhujaev** [kinescope/react-kinescope-player#8]
I have error while using @kinescope/react-kinescope-player.I have like this error. I think problem with localstorage. Because when i clear localstorage it works
Versions: 
@kinescope/react-kinescope-player : 0.4.4
react: 17.0.2
react-router-dom : 5
react-dom : 17.0.2

**Comment by vladzdev** [comment]
Please, provide an example (on codesanbox, etc) with that error.
